"""source_documents chunk-level id plus doc_id grouping column

Revision ID: 3cc1ab7c7f05
Revises: 5b5095243f06
Create Date: 2026-09-15 07:33:16.867085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc1ab7c7f05'
down_revision: Union[str, None] = '5b5095243f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('doc_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_source_documents_doc_id'), 'source_documents', ['doc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_documents_doc_id'), table_name='source_documents')
    op.drop_column('source_documents', 'doc_id')
    # ### end Alembic commands ###
