"""escalation_items: add reason, classification snapshot, resolution_summary

Revision ID: 6134f0419df7
Revises: 7bee451cb081
Create Date: 2026-09-15 13:09:49.979549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6134f0419df7'
down_revision: Union[str, None] = '7bee451cb081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escalation_items', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('escalation_items', sa.Column('product_classification', sa.String(), nullable=True))
    op.add_column('escalation_items', sa.Column('jurisdiction', sa.String(), nullable=True))
    op.add_column('escalation_items', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('escalation_items', sa.Column('confidence_level', sa.String(), nullable=True))
    op.add_column('escalation_items', sa.Column('resolution_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escalation_items', 'resolution_summary')
    op.drop_column('escalation_items', 'confidence_level')
    op.drop_column('escalation_items', 'confidence_score')
    op.drop_column('escalation_items', 'jurisdiction')
    op.drop_column('escalation_items', 'product_classification')
    op.drop_column('escalation_items', 'reason')
    # ### end Alembic commands ###
